
# resume information
resume-index = 314432
seed = 7469868021057329779
rate = 500       
shard = 1/1
nocapture = servername

output-filename = /tmp/tmp3_go8kkj.json
output-format = json

adapter-ip = 192.168.8.145
# TARGET SELECTION (IP, PORTS, EXCLUDES)
ports = 0-65535
range = 192.168.1.0/24

